micronaut:
  application:
    name: jwtsecurity
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: SampleSecretExampleChangeThisLater