micronaut:
  application:
    name: jwtsecurity
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: SampleSecretExampleChangeThisLater
---
micronaut:
  security:
    token:
      jwt:
        generator:
          refresh-token:
            secret: 'pleaseChangeThisSecretForANewOne'